include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    no_leading_underscores_for_local_identifiers: false
    file_names: false
    curly_braces_in_flow_control_structures: false
    prefer_const_constructors: true
    